Japanese translation of guidelines 2020 (section 1 to 11)
kotarot/wca-regulations-translations pull request #61
Opened 2020-02-11 12:16 UTC by sakabar

2020年競技規程のうち、ガイドラインの1章から11章を翻訳しました。

英語版差分
https://github.com/thewca/wca-regulations/compare/official-2019-05-01...official-2020-01-01

2020-02-11 12:20 UTC, sakabar commented on japanese/wca-guidelines.md
> +- 2i2a+) [追記] カメラの画面は、今映している映像が表示されていない時に限り、競技者から見える向きにすることができる。
訳しにくかったところです。伝わりやすさを考えると、逆転させたほうがいいかもしれません。

「カメラの画面は、今映している映像が表示されている場合は競技者から見える向きにしてはならない。」

2020-02-11 12:20 UTC, sakabar commented on japanese/wca-guidelines.md
> +- 2k6+) [明示] WCA 代理人の裁量は、競技者が試技に重大な不利益を与える（例：時間や大会の人員・資源を浪費する）ことを防ぐためだけに使われるのが望ましい。競技者は持てる能力の限りを尽くして試技をしているならば、「悲惨な」結果によって失格とされるべきではない。
"poor" は 「悲惨な」でよい? 「下手な」?

2020-02-11 12:20 UTC, sakabar commented on japanese/wca-guidelines.md
> +- 3j++) [明示] クロックでは、ピンは同じ側の別のピンと区別することができてもよい。
クロックがわからないのですが、これであってますか?

2020-02-13 03:26 UTC, kawam1123 commented on japanese/wca-guidelines.md
> +- 2i2a+) [追記] カメラの画面は、今映している映像が表示されていない時に限り、競技者から見える向きにすることができる。
冗長な訳にしてみるのはどうでしょう。
`「カメラの画面にカメラが映している映像が表示されていない時に限り、カメラの画面を競技者から見える向きにすることができる」`

冒頭を削っても意味は取れるかもしれません。
`「カメラが映している映像が表示されていない時に限り、カメラの画面を競技者から見える向きにすることができる」`

2020-02-13 03:28 UTC, kawam1123 commented on japanese/wca-guidelines.md
> +- 2k6+) [明示] WCA 代理人の裁量は、競技者が試技に重大な不利益を与える（例：時間や大会の人員・資源を浪費する）ことを防ぐためだけに使われるのが望ましい。競技者は持てる能力の限りを尽くして試技をしているならば、「悲惨な」結果によって失格とされるべきではない。
**「下手な」あるいは「悪い」**くらいでもよいかもしれません。学校の成績が悪いことを poor performanceと言ったりしますので、そのくらいのカジュアルな意味だろうかと思います。

2020-02-13 07:34 UTC, hanwu85 commented on japanese/wca-guidelines.md
> +- 3j++) [明示] クロックでは、ピンは同じ側の別のピンと区別することができてもよい。
合っていると思います。

2020-02-13 07:41 UTC, hanwu85 commented on japanese/wca-guidelines.md
> +- 2k6+) [明示] WCA 代理人の裁量は、競技者が試技に重大な不利益を与える（例：時間や大会の人員・資源を浪費する）ことを防ぐためだけに使われるのが望ましい。競技者は持てる能力の限りを尽くして試技をしているならば、「悲惨な」結果によって失格とされるべきではない。
ここのpoor resultは「良くない結果」、「悪い結果」と思っています。（頑張っていましたのに、結果は良くない）

2020-02-14 15:08 UTC, kotarot requested changes
@sakabar お疲れ様です！レビューしました。確認と修正をお願いします 🙇

2020-02-14 15:08 UTC, kotarot commented on japanese/wca-guidelines.md
> +- 2i+++) [注意] Bluetooth パズルは電子的な機器と見なされる。
用語の統一
```suggestion
- 2i+++) [注意] Bluetooth パズルは電子機器と見なされる。
```

2020-02-14 15:08 UTC, kotarot commented on japanese/wca-guidelines.md
> +- 2i2a+) [追記] カメラの画面は、今映している映像が表示されていない時に限り、競技者から見える向きにすることができる。
川村さんの修正案で +1 です！

2020-02-14 15:08 UTC, kotarot commented on japanese/wca-guidelines.md
> +- 2k6+) [明示] WCA 代理人の裁量は、競技者が試技に重大な不利益を与える（例：時間や大会の人員・資源を浪費する）ことを防ぐためだけに使われるのが望ましい。競技者は持てる能力の限りを尽くして試技をしているならば、「悲惨な」結果によって失格とされるべきではない。
これは追加と見せかけて 2019-05-01 version の A1c+ が移動してきただけなので、そのままコピペで
```
[明示] 競技者が大会に悪影響を及ぼすような場合（時間や大会リソースを無駄にする場合等）にのみ、WCA 代理人に裁量が与えられることが望ましい。競技者を、最善を尽くしたときの「悪い」結果により、失格にしないほうが望ましい。
```
でよいと思います。

2020-02-14 15:08 UTC, kotarot commented on japanese/wca-guidelines.md
> +- 3j++) [明示] クロックでは、ピンは同じ側の別のピンと区別することができてもよい。
合ってます！ただ冗長なので
```suggestion
- 3j++) [明示] クロックでは、ピンは同じ側の別のピンと区別できてもよい。
```

2020-02-14 15:08 UTC, kotarot commented on japanese/wca-guidelines.md
> +- 11e++) [推奨] WCA 代理人は追加試技を行う理由を記録する必要がある（例：記録用紙の裏に記録）。
言い回しを統一したいです。
```suggestion
- 11e++) [推奨] WCA 代理人は追加試技の理由を記録することが望ましい（例：記録用紙の裏に記録）。
```

2020-02-15 13:55 UTC, sakabar commented on japanese/wca-guidelines.md
> +- 2i2a+) [追記] カメラの画面は、今映している映像が表示されていない時に限り、競技者から見える向きにすることができる。
ありがとうございます、後者でいきます。

2020-02-15 13:56 UTC, sakabar commented on japanese/wca-guidelines.md
> +- 2k6+) [明示] WCA 代理人の裁量は、競技者が試技に重大な不利益を与える（例：時間や大会の人員・資源を浪費する）ことを防ぐためだけに使われるのが望ましい。競技者は持てる能力の限りを尽くして試技をしているならば、「悲惨な」結果によって失格とされるべきではない。
移動に気付いていませんでした、寺田さんの言うようにそっくりコピペで対応します

2020-02-15 14:18 UTC, sakabar commented
レビューありがとうございました、修正を反映しました。

2020-02-16 10:34 UTC, kotarot approved these changes
@sakabar 早速対応いただきましてありがとうございます！LGTMです。このままmasterにマージはできないので、https://github.com/kotarot/wca-regulations-translations/pull/63 でcherry-pickして集約します。続きはそちらでディスカッションしましょう。

2020-02-16 10:42 UTC, closed without merging