Update Japanese Translation (Regulations 2020.01.01, section 1 to 12)
kotarot/wca-regulations-translations pull request #62
Opened 2020-02-13 03:42 UTC by kawam1123

WCA 大会規則(2020年1月1日版)の1節～12節までを日本語訳しました。

ガイドラインから規則に移動したもの
試技→ソルブ、といった用語の変更
足競技廃止に関する修正
などあります。

2020-02-13 03:55 UTC, kawam1123 commented on japanese/wca-regulations.md
> +        - 3h2a) 透過パーツを含み、パズルの状態についての追加的な情報を与えるようなパズルは使用を許可されない。例外：透明なステッカーあるいはロゴ（参照：[規則 3l](regulations:regulation:3l)）。
透過パーツのあるパズルに関する規則。
「パズルの状態について追加的な情報がわかるような」透明パーツがダメであることを明示しています。少し日本語がこなれていませんが、透過パーツが含まれていることでどのようにダメであるのかを明示したものと理解しています。

2020-02-13 03:56 UTC, kawam1123 commented on japanese/wca-regulations.md
> +    - 7f3) 大会運営チームはスタックマットタイマーによく起こる事故の対策となるような工夫を施す必要がある。対策とは、ボタンが故意でない状況で押されないようにする（例：O リングをボタンの周囲に貼り付ける）ことや電池を固定する（例：電池入れの隙間を埋める）ことである。
ガイドラインに記載のあった項目なので、過去のガイドライン（日本語訳）にあったものをほぼ流用しました。

2020-02-13 09:12 UTC, hanwu85 commented on japanese/wca-regulations.md
> +    - 5b5) ソルブの終わりにパズルの一部のパーツが物理的に離れている、あるいは完全に配置されていない場合、以下の規則が適用される：
`ソルブの終わり前に`だと思います。

2020-02-14 15:26 UTC, kotarot requested changes
@kawam1123 お疲れ様です。作業ありがとうございます！半分ぐらい形式的な指摘になっちゃったのですが、レビューしました。確認していただけますか？

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +    - 2k6) 出場種目に参加するための条件（例：そのパズルの解き方を知っている）を満たしていない場合。競技者はDNF や意図的に悪い結果が予期される場合は競技してはならない。
超細かくて申し訳ないんですが、英単語の前後は半角スペースを空けるというスタイルガイドでやっているため、
```suggestion
    - 2k6) 出場種目に参加するための条件（例：そのパズルの解き方を知っている）を満たしていない場合。競技者は DNF や意図的に悪い結果が予期される場合は競技してはならない。
```

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +    - 3a4) パズルは電子部品（例：BluethoodやWi-Fi機能、モーター、センサー、照明）を含んではならない。（参照：[規則 2i](regulations:regulation:2i)）。
こちらも形式的な修正で申し訳ないです。あと Bluetooth のスペルミス
```suggestion
    - 3a4) パズルは電子部品（例：Bluetooth や Wi-Fi 機能、モーター、センサー、照明）を含んではならない。（参照：[規則 2i](regulations:regulation:2i)）。
```

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +        - 3h2a) 透過パーツを含み、パズルの状態についての追加的な情報を与えるようなパズルは使用を許可されない。例外：透明なステッカーあるいはロゴ（参照：[規則 3l](regulations:regulation:3l)）。
承知しました！問題ないと思います。

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +    - 5b5) ソルブの終わりにパズルの一部のパーツが物理的に離れている、あるいは完全に配置されていない場合、以下の規則が適用される：
`at the end of the solve` なので、ソルブの終わりにで問題ないと思います。

他の関連条文との言い回しを統一して
```suggestion
    - 5b5) ソルブ終了時にパズルの一部のパーツが物理的に離れている、あるいは完全に配置されていない場合、以下の規則が適用される：
```
がよい良いと思います。

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +        - 12a4a) 時計回りに 90 度：x（RまたはL'と同じ方向）、y（UまたはD'と同じ方向）、z（FまたはB'と同じ方向）。
これも形式的な修正となりますが、アルファベットの前後は半角スペースを空ける（ただし句読点と括弧との間は空けなくてよい）というスタイルガイドなので
```suggestion
        - 12a4a) 時計回りに 90 度：x（R または L' と同じ方向）、y（U または D' と同じ方向）、z（F または B' と同じ方向）。
```

2020-02-14 15:26 UTC, kotarot commented on japanese/wca-regulations.md
> +        - 12a4b) 反時計回りに 90 度：x'（R'またはLと同じ方向）、y'（U'またはDと同じ方向）、z'（F'またはBと同じ方向）。
```suggestion
        - 12a4b) 反時計回りに 90 度：x'（R' または L と同じ方向）、y'（U' または D と同じ方向）、z'（F' または B と同じ方向）。
```

2020-02-14 15:31 UTC, kotarot commented
あとこのPRに今回と全然関係ないコミットが入っちゃってますが、後ほどcherry-pickしますので特に気にしなくて大丈夫です。

2020-02-15 03:23 UTC, hanwu85 commented on japanese/wca-regulations.md
> +    - 5b5) ソルブの終わりにパズルの一部のパーツが物理的に離れている、あるいは完全に配置されていない場合、以下の規則が適用される：
間違いました、確かに寺田さんは正しいです。

2020-02-15 04:56 UTC, sakabar commented on japanese/wca-regulations.md
> +    - 4b3) スクランブルプログラムの仕様として、公式のスクランブル手順は解くのに 2 手以上要する全ての状態からのランダムの状態（各状態は等確率）でなければならない。以下の追記または例外が適用される。
「の」の連続が気になっています。曖昧性を減らすために、下記のように「〜選ばれた」と補うのはいかがでしょうか。

日本語での差分範囲を広げて、以下でいかがでしょうか。
```suggestion
    - 4b3) スクランブルプログラムの仕様として、公式のスクランブル手順は解くのに 2 手以上要する全ての状態からランダムに選ばれた状態（各状態は等確率）でなければならない。以下の追記または例外が適用される。
```

2020-02-16 11:08 UTC, kotarot commented on japanese/wca-regulations.md
> +    - 4b3) スクランブルプログラムの仕様として、公式のスクランブル手順は解くのに 2 手以上要する全ての状態からのランダムの状態（各状態は等確率）でなければならない。以下の追記または例外が適用される。
採用します！

2020-02-16 11:37 UTC, kotarot commented
このPRでの修正も https://github.com/kotarot/wca-regulations-translations/pull/63 に取り込んで集約したので続きはそちらでディスカッションしましょう！

2020-02-16 11:37 UTC, closed without merging